# Generated by Django 5.2.3 on 2025-06-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fitness_class',
            new_name='class_id',
        ),
    ]
